SUPPORTED_FILE_EXTENSIONS = {".pdf", ".docx"}

INPUT_TYPE_TEXT_ONLY = "text_only"
INPUT_TYPE_TEXT_WITH_FILE = "text_with_file"
INPUT_TYPE_INVALID = "invalid"

ERROR_MISSING_QUESTION = "MISSING_QUESTION"
ERROR_FILE_ONLY_NOT_ALLOWED = "FILE_ONLY_NOT_ALLOWED"
ERROR_FILE_NOT_FOUND = "FILE_NOT_FOUND"
ERROR_UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
ERROR_FILE_TEXT_EXTRACTION_FAILED = "FILE_TEXT_EXTRACTION_FAILED"
ERROR_PDF_TEXT_NOT_FOUND = "PDF_TEXT_NOT_FOUND"
ERROR_INTERNAL_PROCESSING = "INTERNAL_PROCESSING_ERROR"
